// Copyright (c) 2025 Eclipse Foundation.
// 
// This program and the accompanying materials are made available under the
// terms of the MIT License which is available at
// https://opensource.org/licenses/MIT.
//
// SPDX-License-Identifier: MIT

import type { Metadata, Viewport } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import ColorThemeProvider from "../components/ColorThemeProvider";
import { getThemeStyles } from "../lib/theme-server";


// Configure Shantell Sans (commented out as not currently used)
// const shantell_sans = Shantell_Sans({
//   subsets: ['latin'], // Specify the desired subsets (e.g., 'latin', 'latin-ext', 'cyrillic', etc.)
//   display: 'swap',   // 'swap' is generally recommended for FOUT (Flash of Unstyled Text)
//                       // 'optional' can also be used for minimal layout shift
//   variable: '--font-sans', // Optional: define a CSS variable for easy use
// });

const quicksand = Quicksand({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-content',
});


// const shantell_mono = Shantell_Mono({
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-mono', // CSS variable for Shantell Mono
// });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Learning Journey",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#4a7c6b", // --color-primary-500
  colorScheme: "light",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fetch theme server-side to prevent flash
  const themeStyles = await getThemeStyles();

  return (
    <html lang="en">
      <head>
        {/* Inject theme styles before main CSS loads */}
        <style dangerouslySetInnerHTML={{ __html: themeStyles }} />
      </head>
      <body
        className={`h-screen w-screen overflow-y-auto ${quicksand.variable} antialiased`}
      >
        {/* ${shantell_sans.variable} */}
        {/* <div className="w-full h-20 bg-slate-500 text-white flex items-center justify-center">I am header </div> */}
        <ColorThemeProvider>
          {children}
        </ColorThemeProvider>
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
